### ISSUE TITLE
"searching stamina bar" 

### ISSUE THREAD

**Issue by man8000** [fr0st-iwnl/kiyokomacro#1]
im trying to use the treadmill macro but it won't do anything and keeps saying "searching stamina bar" idk if im missing something or what

**Comment by fr0st-iwnl** [comment]
Temporary fix for the new UI update

1. Download Bloxstrap https://github.com/pizzaboxer/bloxstrap/releases
2. Go to "FastFlags" tab
3. Change "Preferred escape menu version" from Default to **Version 2 (2020)**
4.  Open the Browser Roblox


if this didn't work join the discord server and read #faq
