### ISSUE TITLE
Fat Bunner

### ISSUE THREAD

**Issue by kenzomagic** [fr0st-iwnl/kiyokomacro#10]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Did you check the FAQ? *

- [X] I have read the FAQ.

### Description

When stating the macro it bugs every time even though i have no food and says status not found and spam pops fat bunners.

### How to reproduce

Find out how to fix it saying status not found.

### Images, Videos

![image_2024-11-24_091349623](https://github.com/user-attachments/assets/a09f4995-a66c-4f11-9261-dc92806be7eb)

**Comment by fr0st-iwnl** [comment]
could you maybe send a video?

**Comment by fr0st-iwnl** [comment]
Closing this issue because the user didn’t respond.
