### ISSUE TITLE
Hello when i try macro my sp the macro goes away

### ISSUE THREAD

**Issue by Richardthedemon** [fr0st-iwnl/kiyokomacro#11]
### Already searched for help? *

- [X] I have searched the existing open and closed issues.

### Did you check the FAQ? *

- [X] I have read the FAQ.

### What Help Do You Need?

Hello when i try macro my sp the macro goes away

### Your Setup

window 11 rdp

### Images or Videos

no

**Comment by Richardthedemon** [comment]
你能让宏不使用锁吗 ？？？

**Comment by Richardthedemon** [comment]
pleas make the macro not use the lock for rdp im beg of kiyoko macro 🙏🙏🥲🥲

**Comment by Richardthedemon** [comment]
非常感谢 kiyoko 宏，你是最好的宏所有者，请让宏为我的 rdp 工作，我求你非常美丽，一位中国人，一位日本人，谢谢你让宏在 rdp 上工作

**Comment by fr0st-iwnl** [comment]
Closing this issue because you didn’t follow the requirements, and I can’t understand you if you’re not speaking in English.

**Comment by Richardthedemon** [comment]
🙏🙏🙏

**Comment by Richardthedemon** [comment]
no plese
