### ISSUE TITLE
not working for me (as far as I'm aware, just me)

### ISSUE THREAD

**Issue by TodoOtacone** [fr0st-iwnl/kiyokomacro#17]
### Already searched for help? *

- [X] I have searched the existing open and closed issues.

### Did you check the FAQ? *

- [X] I have read the FAQ.

### What Help Do You Need?

I have the "Searching for stamina bar" issue, though it used to work for me fine. I tried everything on the FAQ page, and nothing helps. It seems to work for a moment if i escape to the roblox menu, and then it breaks again.

### Your Setup

I'm using the latest versions, and as far as im aware, my setup is standard, but videos may help more, so ill attach those.

### Images or Videos

https://github.com/user-attachments/assets/284941fd-dbb2-4f7c-924a-f729297b31f8

had to lower the quality of the video a shit ton so github would actually let me attach it, sorry about that. there was another video as well but I couldnt get the file size small enough, sorry.

**Comment by TodoOtacone** [comment]
just noticed that the macro popup in the corner didnt show up on the video for some reason? I can rerecord but I dont know how to get them to show up.

**Comment by fr0st-iwnl** [comment]
You need to be on the treadmill to start the macro. I noticed you started the macro without being on the treadmill, which might explain why that issue occurred.

**Comment by TodoOtacone** [comment]
Sorry for keeping the issue open, I had figured out it was my computer using auto HDR when I was messing with settings this morning. I’ll close the issue now, thank you for trying to help.
