### ISSUE TITLE
Image send Directory not found

### ISSUE THREAD

**Issue by NaturallyAdeft** [fr0st-iwnl/kiyokomacro#18]
### Already searched for help? *

- [X] I have searched the existing open and closed issues.

### Did you check the FAQ? *

- [X] I have read the FAQ.

### What Help Do You Need?

When it takes a screenshot to send to my webhook it says that the directory was not found ive tried editing the directory to try and fix it but nothing has not worked for me ive also noticed that there isint a pictures thing in my users folder so idk what to do abt that

### Your Setup

newest version

**Comment by fr0st-iwnl** [comment]
Can you try pressing Print Screen in Roblox, check if a screenshot appears in the Roblox pictures folder, and test the macro again. Also, make sure not to delete the picture.

**Comment by NaturallyAdeft** [comment]
hey its not the screenshot thing thats the problem is just that whenever it takes the screenshot it cant find the folder that te screenshot is in and sent it to my webhook

**Comment by fr0st-iwnl** [comment]
Yeah, I know, but I asked you to press Print Screen to take a screenshot so the Roblox Pictures folder gets created. Also, do you have anything in that folder, or is it empty, or does it not exist at all?

**Comment by NaturallyAdeft** [comment]
i already have some screenshots from when i was trying to fix it myself in that folder and it exists it just doesint show up in my users folder for some reason so ive tried changing it just to pictures and just to make sure its this one right?
![1123](https://github.com/user-attachments/assets/6184165e-f67b-4699-893a-f0f89ba7b08a)

**Comment by fr0st-iwnl** [comment]
Can you check if navigating to `C:\Users\user\Pictures\Roblox` takes you to the correct folder? Make sure to replace "user" with your actual username to verify the path and lmk

**Comment by fr0st-iwnl** [comment]
> i already have some screenshots from when i was trying to fix it myself in that folder and it exists it just doesint show up in my users folder for some reason so ive tried changing it just to pictures and just to make sure its this one right? ![1123](https://private-user-images.githubusercontent.com/189780691/390127824-6184165e-f67b-4699-893a-f0f89ba7b08a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTIzMzYsIm5iZiI6MTczMjY1MjAzNiwicGF0aCI6Ii8xODk3ODA2OTEvMzkwMTI3ODI0LTYxODQxNjVlLWY2N2ItNDY5OS04OTNhLWYwZjg5YmE3YjA4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQyMDEzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDgyYTAzNWQ4MTQwMDZlNjkyMThjNzRkZWZlMWM4M2I2MzZmMTc1YjQzYjcwNjI3MTk3M2MwOTE4OTkxZTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lPaSGJs2vptMG651E8pN4G8S279-qipMIZdtYkIuW_M)

and yeah this is where the Roblox folder should be

**Comment by NaturallyAdeft** [comment]
> Can you check if navigating to `C:\Users\user\Pictures\Roblox` takes you to the correct folder? Make sure to replace "user" with your actual username to verify the path and lmk

im pretty sure ive alr tried this but ill try again because the problem is that that picture folder does not show up in my user

**Comment by fr0st-iwnl** [comment]
Yeah, but what I’m trying to say is, try pressing Print Screen while you're in Roblox to take a screenshot, and maybe the folder will get created. If it still doesn’t create the folder, try creating it manually in the Pictures folder. If that still doesn’t work, I’m not sure what else to do this is where Roblox saves the pictures.

**Comment by NaturallyAdeft** [comment]
yea it still said the same thing
![image](https://github.com/user-attachments/assets/e8226550-a113-42a2-b611-8d35f8907aa6)

**Comment by NaturallyAdeft** [comment]
yea it takes me to the roblox folder its just that its not in the users folder its just under "this PC" and i dont klnow how to make a directory to that

**Comment by fr0st-iwnl** [comment]
> yea it takes me to the roblox folder its just that its not in the users folder its just under "this PC" and i dont klnow how to make a directory to that

That doesn't make sense to me at all. Can you show me the path where Roblox saves the pictures for you? I really wanna see it.

**Comment by NaturallyAdeft** [comment]
![image](https://github.com/user-attachments/assets/5ca966cc-18e9-453e-942b-32a87b32976b)
this is what it looks like

**Comment by fr0st-iwnl** [comment]
> C:\Users\user\OneDrive\Pictures\Roblox

Yeah, I see the issue now. The macro doesn’t detect files saved in **OneDrive** it only detects files in `C:\Users\user\Pictures\Roblox`. If you want the macro to send images, you'll either need to remove **OneDrive** or add the **OneDrive** path to the macro’s [source code](https://github.com/fr0st-iwnl/kiyokomacro/blob/main/Kiyoko's%20Macro.ahk#L2139). I’m closing this issue for now.
