### ISSUE TITLE
Dura

### ISSUE THREAD

**Issue by Kingaxxu** [fr0st-iwnl/kiyokomacro#21]
### Already searched for help? *

- [X] I have searched the existing open and closed issues.

### Did you check the FAQ? *

- [X] I have read the FAQ.

### What Help Do You Need?

the dura macro only rhythm

**Comment by fr0st-iwnl** [comment]
You did not provide enough details about your issue so I will close it. The Dura macro can either charge Rhythm or ignore it by selecting **"Do Nothing"**. If you think this is a bug please open a new issue in the bug section with a video showing the problem.
