### ISSUE TITLE
SP Running

### ISSUE THREAD

**Issue by BlueYolotall** [fr0st-iwnl/kiyokomacro#25]
### Already reported? *

- [X] I have searched the existing open and closed issues.

### Your Question

Why does my macro when I am macroing SP, at some point, the running on my character moves a little backward instead of staying in a place which ruins the training?

**Comment by fr0st-iwnl** [comment]
The macro moves you a little bit so your character keeps running, but be careful with the punching bag because it can also move you backward a bit and mess up your macro.
