### ISSUE TITLE
Macro doesnt work for muscle

### ISSUE THREAD

**Issue by Lolerbuttbutt** [fr0st-iwnl/kiyokomacro#3]
when ever i try to macro muscle and it goes to start it doesnt start the machine nor does it click anything ive even tried starting it for the macro to nothing working please help me fix this

**Comment by fr0st-iwnl** [comment]
Please first read the FAQ at https://kiyokosmacros.netlify.app/faq to see if your issue is addressed there. If not, try uploading a picture of the problem here on GitHub. For videos, you can upload them to a platform like Streamable or YouTube and share the link.

**Comment by Lolerbuttbutt** [comment]
i dont know hot to record it but whenever i start the macro literally nothing happens
and i followed the FAQ

**Comment by fr0st-iwnl** [comment]
Record it with OBS or something similar. If you can't send a video or a picture, I can't help you and we'll need to close this issue.

**Comment by fr0st-iwnl** [comment]
Closing this issue because the user has not responded.
