### ISSUE TITLE
Macro is really slow sometimes especially when weight training and using lifter apt

### ISSUE THREAD

**Issue by Thomponv2** [fr0st-iwnl/kiyokomacro#4]
Title, sometimes it takes like a second or longer for macro to register the yellow dot, when using lifter apt it seems like it doesn't even take that into account, is there any way to make the macro faster?

**Comment by fr0st-iwnl** [comment]
Since the macro is open source, you can modify the source code to improve its performance. Also, please note that green or yellow skin tones and gym lighting from above can affect how well the macro works.

**Comment by Thomponv2** [comment]
after trying to make the macro better i come to the conclussion that ahk is retarded and stupidly slow
