### ISSUE TITLE
treds

### ISSUE THREAD

**Issue by Redroverl** [fr0st-iwnl/kiyokomacro#5]
whenever i run the tred macro it always misses over 1-3 keys and it makes me full bar at the end of the 60 seconds causing me to gain little to no stam

**Comment by fr0st-iwnl** [comment]
The issue might be related to your camera positioning, which affects how the macro captures and searches the image. Try placing the camera in the middle. Also, make sure your keyboard language is set to English [US].

**Comment by Redroverl** [comment]
https://github.com/user-attachments/assets/f3172b23-0987-4a05-8b7c-d0281661cfa6

No just tried doing what you said and the problem still remains and i recorded a run that's on the tamer side its much worse most of the time

**Comment by fr0st-iwnl** [comment]
> Untitled.video.-.Made.with.Clipchamp.mp4
> 
> No just tried doing what you said and the problem still remains and i recorded a run that's on the tamer side its much worse most of the time

I see the issue now its cause of the VC turn it off and the macro should work.

**Comment by Redroverl** [comment]
Oh it worked deeply appreciate it man
