### ISSUE TITLE
SP macro doesnt work

### ISSUE THREAD

**Issue by MorvidGB** [fr0st-iwnl/kiyokomacro#8]
the macro only punches, when i start it, wether i hold style or not, it just spams m1 and does nothing else.

**Comment by fr0st-iwnl** [comment]
Do you have the new Roblox UI?

**Comment by Kingaxxu** [comment]
I got this problem too and i have the new roblox ui

**Comment by fr0st-iwnl** [comment]
> I got this problem too and i have the new roblox ui

## New UI

If u have this new **UI** use the [Bloxstrap.bat](https://github.com/fr0st-iwnl/kiyokomacro/tree/main/BloxstrapUI) to revert it and read the [FAQ](https://kiyokosmacros.netlify.app/faq)
![image](https://github.com/user-attachments/assets/360cf942-6dd1-462a-917b-73bfb9c0484e)


## Old UI

After switching to this **UI**, the macro should work.

![image](https://github.com/user-attachments/assets/86b34185-e4b7-460e-a735-d80c005dba94)

**Comment by Kingaxxu** [comment]
TY it work now

**Comment by fr0st-iwnl** [comment]
@MorvidGB You probably have the same issue, so i'm closing this for now.
